services:
  #! Telemetry
  otel-agent:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.126.0
    ports: [4317:4317]
    environment:
      - HONEYCOMB_DATASET=${HONEYCOMB_DATASET}
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
    command: --config=/etc/otel-agent-config.yaml
    volumes: ["./dev/otel-agent-config.yaml:/etc/otel-agent-config.yaml"]

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    ports: [8081:8080]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-pg:5432/default
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: secret
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8081
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    command: start-dev --import-realm
    depends_on: [keycloak-pg]
    volumes:
      - "./dev/keycloak:/opt/keycloak/data/import"

  oathkeeper:
    image: oryd/oathkeeper:v0.40.7-distroless
    ports: [4455:4455, 4456:4456]
    command: serve -c /home/ory/oathkeeper.yml --sqa-opt-out
    volumes: ["./dev/ory:/home/ory"]
    depends_on: [keycloak, otel-agent]

  mailcrab:
    image: marlonb/mailcrab:latest
    ports: [1025:1025, 1080:1080]

  #! Databases
  core-pg:
    image: postgres:17.5
    ports: [5433:5432]
    environment:
      [POSTGRES_USER=user, POSTGRES_PASSWORD=password, POSTGRES_DB=pg]

  keycloak-pg:
    image: postgres:17.5
    ports: [5437:5432]
    environment:
      [POSTGRES_USER=dbuser, POSTGRES_PASSWORD=secret, POSTGRES_DB=default]
